name: gestion_produit_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.0
  flutter_stripe: ^9.5.0
  flutter_dotenv: ^5.1.0
  country_code_picker: ^3.0.0
  card_swiper: ^3.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^2.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/icons/back.svg
    - assets/icons/search.svg
    - assets/icons/search_icon.svg
    - assets/icons/cart.svg
    - assets/icons/add_to_cart.svg
    - assets/icons/email.svg
    - assets/icons/password.svg
    - assets/icons/list.png

    - assets/icons/profile_icon.svg

    - assets/icons/search_icon.svg
    - assets/icons/cart_icon.svg
  