spring.application.name=gestionproduit

# Connexion � ta base de donn�es
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_produits
spring.datasource.username=root
spring.datasource.password=

# JPA (pour que Spring cr�e les tables automatiquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Encodage
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
server.address=0.0.0.0
stripe.secret.key=sk_test_51OHotbIUNFbNVA8jKmPysVIRp7D8UsENtR2DrUiwRZlKwmcBBilKGG4UXNBxjXnk6LcTukxPndb3SoxoCA6PFg5b00QeQtkZ08
jwt.secret=votreCleSecreteTresLongueEtSecurisee1234567890

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=unityforce.dev@gmail.com
spring.mail.password=riti ojdx murd hbnw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true